language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- pypy
- pypy3
install:
- pip install -e .
- pip install coveralls
script:
- coverage run --source=trueskill setup.py test
after_success:
- coveralls
