application: multi-day-ladder
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /bootstrap
  static_dir: bootstrap  
- url: /.*
  script: urls.application
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
